copy: strm_copy.c
	gcc -o main_cpy strm_copy.c

c_count: strm_count.c
	gcc -o main_s_cnt strm_count.c

l_count: line_count.c
	gcc -o main_l_cnt line_count.c

w_count: word_count.c
	gcc -o main_w_cnt word_count.c

clean:
	rm -f main_*
